apiVersion: batch/v1
kind: Job
metadata:
  name: taskapp-migrate
  namespace: taskapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/ts-a-devops/taskapp-backend@sha256:7ebe1b93baef2c95098d6ce253879b4067ffbe39645a9c4fa5513aff202e4a70
          args: ["true"]
          envFrom:
            - configMapRef:
                name: taskapp-config
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: DATABASE_PASSWORD
