[control_plane]
k3s-server ansible_host=3.94.83.144 private_ip=10.0.1.203

[workers]
k3s-worker-0 ansible_host=100.30.225.103
k3s-worker-1 ansible_host=13.220.231.117

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/capstone-phoenix
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
