[control_plane]
k3s-server ansible_host=34.207.179.67 private_ip=10.0.1.51

[workers]
k3s-worker-0 ansible_host=34.229.23.159
k3s-worker-1 ansible_host=52.90.99.55

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/capstone-phoenix
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
